const curriculumData = {
    Telugu: {
        1: [
            { word: "Namaskaram", nativeWord: "నమస్కారం", meaning: "Hello", transliteration: "na-mas-ka-ram" },
            { word: "Dhanyavadalu", nativeWord: "ధన్యవాదాలు", meaning: "Thank you", transliteration: "dhan-ya-va-da-lu" },
            { word: "Swagatam", nativeWord: "స్వాగతం", meaning: "Welcome", transliteration: "swa-ga-tam" },
            { word: "Bagunnara", nativeWord: "బాగున్నారా", meaning: "How are you?", transliteration: "ba-gun-na-ra" },
            { word: "Naa peru", nativeWord: "నా పేరు", meaning: "My name is", transliteration: "naa-pe-ru" },
            { word: "Selavu", nativeWord: "సెలవు", meaning: "Goodbye", transliteration: "se-la-vu" },
            { word: "Avunu", nativeWord: "అవును", meaning: "Yes", transliteration: "a-vu-nu" },
            { word: "Kaadu", nativeWord: "కాదు", meaning: "No", transliteration: "kaa-du" },
            { word: "Kshaminchandi", nativeWord: "క్షమించండి", meaning: "Sorry", transliteration: "ksha-min-chan-di" },
            { word: "Subhodayam", nativeWord: "శుభోదయం", meaning: "Good morning", transliteration: "su-bho-da-yam" }
        ],
        2: [
            { word: "Amma", nativeWord: "అమ్మ", meaning: "Mother", transliteration: "am-ma" },
            { word: "Nanna", nativeWord: "నాన్న", meaning: "Father", transliteration: "nan-na" },
            { word: "Anna", nativeWord: "అన్న", meaning: "Elder Brother", transliteration: "an-na" },
            { word: "Tammudu", nativeWord: "తమ్ముడు", meaning: "Younger Brother", transliteration: "tam-mu-du" },
            { word: "Akka", nativeWord: "అక్క", meaning: "Elder Sister", transliteration: "ak-ka" },
            { word: "Chelli", nativeWord: "చెల్లి", meaning: "Younger Sister", transliteration: "chel-li" },
            { word: "Thatha", nativeWord: "తాత", meaning: "Grandfather", transliteration: "thaa-tha" },
            { word: "Naanamma", nativeWord: "నానమ్మ", meaning: "Grandmother", transliteration: "naa-nam-ma" },
            { word: "Snehitudu", nativeWord: "స్నేహితుడు", meaning: "Friend", transliteration: "sne-hi-thu-du" },
            { word: "Kutumbam", nativeWord: "కుటుంబం", meaning: "Family", transliteration: "ku-tum-bam" }
        ],
        3: [
            { word: "Okati", nativeWord: "ఒకటి", meaning: "One", transliteration: "o-ka-ti" },
            { word: "Rendu", nativeWord: "రెండు", meaning: "Two", transliteration: "ren-du" },
            { word: "Moodu", nativeWord: "మూడు", meaning: "Three", transliteration: "moo-du" },
            { word: "Naalugu", nativeWord: "నాలుగు", meaning: "Four", transliteration: "naa-lu-gu" },
            { word: "Aidu", nativeWord: "ఐదు", meaning: "Five", transliteration: "ai-du" },
            { word: "Aaru", nativeWord: "ఆరు", meaning: "Six", transliteration: "aa-ru" },
            { word: "Edu", nativeWord: "ఏడు", meaning: "Seven", transliteration: "e-du" },
            { word: "Enimidi", nativeWord: "ఎనిమిది", meaning: "Eight", transliteration: "e-ni-mi-di" },
            { word: "Tommidi", nativeWord: "తొమ్మిది", meaning: "Nine", transliteration: "tom-mi-di" },
            { word: "Padi", nativeWord: "పది", meaning: "Ten", transliteration: "pa-di" }
        ],
        4: [
            { word: "Erra", nativeWord: "ఎర్ర", meaning: "Red", transliteration: "er-ra" },
            { word: "Neela", nativeWord: "నీల", meaning: "Blue", transliteration: "nee-la" },
            { word: "Paccha", nativeWord: "పచ్చ", meaning: "Green", transliteration: "pac-cha" },
            { word: "Pasupu", nativeWord: "పసుపు", meaning: "Yellow", transliteration: "pa-su-pu" },
            { word: "Nalupu", nativeWord: "నలుపు", meaning: "Black", transliteration: "na-lu-pu" },
            { word: "Telupu", nativeWord: "తెలుపు", meaning: "White", transliteration: "te-lu-pu" },
            { word: "Chakram", nativeWord: "చక్రం", meaning: "Circle", transliteration: "chak-ram" },
            { word: "Chaturasram", nativeWord: "చతురస్రం", meaning: "Square", transliteration: "cha-thu-ras-ram" },
            { word: "Trikonam", nativeWord: "త్రికోణం", meaning: "Triangle", transliteration: "tri-ko-nam" },
            { word: "Nakshatram", nativeWord: "నక్షత్రం", meaning: "Star", transliteration: "nak-shat-ram" }
        ],
        5: [
            { word: "Annam", nativeWord: "అన్నం", meaning: "Rice/Food", transliteration: "an-nam" },
            { word: "Neeru", nativeWord: "నీరు", meaning: "Water", transliteration: "nee-ru" },
            { word: "Kura", nativeWord: "కూర", meaning: "Curry", transliteration: "kuu-ra" },
            { word: "Pallu", nativeWord: "పళ్ళు", meaning: "Fruits", transliteration: "pal-lu" },
            { word: "Paalu", nativeWord: "పాలు", meaning: "Milk", transliteration: "paa-lu" },
            { word: "Perugu", nativeWord: "పెరుగు", meaning: "Curd", transliteration: "pe-ru-gu" },
            { word: "Chekkeri", nativeWord: "చక్కెర", meaning: "Sugar", transliteration: "chek-ke-ra" },
            { word: "Uppu", nativeWord: "ఉప్పు", meaning: "Salt", transliteration: "up-pu" },
            { word: "Thindi", nativeWord: "తిండి", meaning: "Meal", transliteration: "thin-di" },
            { word: "Rotti", nativeWord: "రొట్టి", meaning: "Bread/Roti", transliteration: "rot-ti" }
        ],
        6: [
            { word: "Thinu", nativeWord: "తిను", meaning: "Eat", transliteration: "thi-nu" },
            { word: "Thagu", nativeWord: "త్రాగు", meaning: "Drink", transliteration: "thaa-gu" },
            { word: "Vellu", nativeWord: "వెళ్ళు", meaning: "Go", transliteration: "vel-lu" },
            { word: "Ra", nativeWord: "రా", meaning: "Come", transliteration: "raa" },
            { word: "Chudu", nativeWord: "చూడు", meaning: "See", transliteration: "chuu-du" },
            { word: "Vinu", nativeWord: "విను", meaning: "Listen", transliteration: "vi-nu" },
            { word: "Maatladu", nativeWord: "మాట్లాడు", meaning: "Speak", transliteration: "maat-la-du" },
            { word: "Nidrapodu", nativeWord: "నిద్రపోవు", meaning: "Sleep", transliteration: "ni-dra-po-vu" },
            { word: "Chaduvu", nativeWord: "చదువు", meaning: "Read/Study", transliteration: "cha-du-vu" },
            { word: "Rayu", nativeWord: "రాయు", meaning: "Write", transliteration: "raa-yu" }
        ],
        7: [
            { word: "Emi", nativeWord: "ఏమి", meaning: "What", transliteration: "e-mi" },
            { word: "Ekkada", nativeWord: "ఎక్కడ", meaning: "Where", transliteration: "ek-ka-da" },
            { word: "Eppudu", nativeWord: "ఎప్పుడు", meaning: "When", transliteration: "ep-pu-du" },
            { word: "Enduku", nativeWord: "ఎందుకు", meaning: "Why", transliteration: "en-du-ku" },
            { word: "Evaru", nativeWord: "ఎవరు", meaning: "Who", transliteration: "e-va-ru" },
            { word: "Ela", nativeWord: "ఎలా", meaning: "How", transliteration: "e-laa" },
            { word: "Enni", nativeWord: "ఎన్ని", meaning: "How many", transliteration: "en-ni" },
            { word: "Edi", nativeWord: "ఏది", meaning: "Which", transliteration: "e-di" },
            { word: "Naadi", nativeWord: "నాది", meaning: "Mine", transliteration: "naa-di" },
            { word: "Meedi", nativeWord: "మీది", meaning: "Yours", transliteration: "mee-di" }
        ],
        8: [
            { word: "Samayam", nativeWord: "సమయం", meaning: "Time", transliteration: "sa-ma-yam" },
            { word: "Roju", nativeWord: "రోజు", meaning: "Day", transliteration: "ro-ju" },
            { word: "Varam", nativeWord: "వారం", meaning: "Week", transliteration: "vaa-ram" },
            { word: "Nela", nativeWord: "నెల", meaning: "Month", transliteration: "ne-la" },
            { word: "Somavaram", nativeWord: "సోమవారం", meaning: "Monday", transliteration: "so-ma-vaa-ram" },
            { word: "Mangalavaram", nativeWord: "మంగళవారం", meaning: "Tuesday", transliteration: "man-ga-la-vaa-ram" },
            { word: "Budhavaram", nativeWord: "బుధవారం", meaning: "Wednesday", transliteration: "bu-dha-vaa-ram" },
            { word: "Guruvaram", nativeWord: "గురువారం", meaning: "Thursday", transliteration: "gu-ru-vaa-ram" },
            { word: "Sukravaram", nativeWord: "శుక్రవారం", meaning: "Friday", transliteration: "suk-ra-vaa-ram" },
            { word: "Sani-Adivaram", nativeWord: "శని-ఆదివారం", meaning: "Weekend", transliteration: "sa-ni-aa-di-vaa-ram" }
        ],
        9: [
            { word: "Thala", nativeWord: "తల", meaning: "Head", transliteration: "tha-la" },
            { word: "Kallu", nativeWord: "కళ్ళు", meaning: "Eyes", transliteration: "kal-lu" },
            { word: "Chevvulu", nativeWord: "చెవ్వులు", meaning: "Ears", transliteration: "chev-vu-lu" },
            { word: "Mukku", nativeWord: "ముక్కు", meaning: "Nose", transliteration: "muk-ku" },
            { word: "Noru", nativeWord: "నోరు", meaning: "Mouth", transliteration: "no-ru" },
            { word: "Chethulu", nativeWord: "చేతులు", meaning: "Hands", transliteration: "chee-thu-lu" },
            { word: "Kaallu", nativeWord: "కాళ్ళు", meaning: "Legs", transliteration: "kaal-lu" },
            { word: "Gunde", nativeWord: "గుండె", meaning: "Heart", transliteration: "gun-de" },
            { word: "Potta", nativeWord: "పొట్ట", meaning: "Stomach", transliteration: "pot-ta" },
            { word: "Vellu", nativeWord: "వేళ్ళు", meaning: "Fingers", transliteration: "veel-lu" }
        ],
        10: [
            { word: "Kukka", nativeWord: "కుక్క", meaning: "Dog", transliteration: "kuk-ka" },
            { word: "Pilli", nativeWord: "పిల్లి", meaning: "Cat", transliteration: "pil-li" },
            { word: "Aavu", nativeWord: "ఆవు", meaning: "Cow", transliteration: "aa-vu" },
            { word: "Enugu", nativeWord: "ఏనుగు", meaning: "Elephant", transliteration: "ee-nu-gu" },
            { word: "Simham", nativeWord: "సింహం", meaning: "Lion", transliteration: "sim-ham" },
            { word: "Chettu", nativeWord: "చెట్టు", meaning: "Tree", transliteration: "chet-tu" },
            { word: "Puvvu", nativeWord: "పువ్వు", meaning: "Flower", transliteration: "puv-vu" },
            { word: "Akasham", nativeWord: "ఆకాశం", meaning: "Sky", transliteration: "aa-kaa-sam" },
            { word: "Suryudu", nativeWord: "సూర్యుడు", meaning: "Sun", transliteration: "suur-yu-du" },
            { word: "Chandrudu", nativeWord: "చంద్రుడు", meaning: "Moon", transliteration: "chan-dru-du" }
        ],
        11: [
            { word: "Illu", nativeWord: "ఇల్లు", meaning: "House", transliteration: "il-lu" },
            { word: "Badi", nativeWord: "బడి", meaning: "School", transliteration: "ba-di" },
            { word: "Karyalayam", nativeWord: "కార్యాలయం", meaning: "Office", transliteration: "kaar-yaa-la-yam" },
            { word: "Angadi", nativeWord: "అంగడి", meaning: "Shop/Market", transliteration: "an-ga-di" },
            { word: "Ooru", nativeWord: "ఊరు", meaning: "Village/Town", transliteration: "oo-ru" },
            { word: "Desham", nativeWord: "దేశం", meaning: "Country", transliteration: "dee-sam" },
            { word: "Dhaari", nativeWord: "దారి", meaning: "Road/Path", transliteration: "dhaa-ri" },
            { word: "Gudi", nativeWord: "గుడి", meaning: "Temple", transliteration: "gu-di" },
            { word: "Vantashala", nativeWord: "వంటశాల", meaning: "Kitchen", transliteration: "van-ta-saa-la" },
            { word: "Gadulu", nativeWord: "గదులు", meaning: "Rooms", transliteration: "ga-du-lu" }
        ],
        12: [
            { word: "Santhosham", nativeWord: "సంతోషం", meaning: "Happy", transliteration: "san-tho-sham" },
            { word: "Badha", nativeWord: "బాధ", meaning: "Sad", transliteration: "baa-dha" },
            { word: "Kopam", nativeWord: "కోపం", meaning: "Angry", transliteration: "ko-pam" },
            { word: "Bhayam", nativeWord: "భయం", meaning: "Fear", transliteration: "bha-yam" },
            { word: "Pedda", nativeWord: "పెద్ద", meaning: "Big", transliteration: "ped-da" },
            { word: "Chinna", nativeWord: "చిన్న", meaning: "Small", transliteration: "chin-na" },
            { word: "Manchi", nativeWord: "మంచి", meaning: "Good", transliteration: "man-chi" },
            { word: "Chedu", nativeWord: "చెడు", meaning: "Bad", transliteration: "che-du" },
            { word: "Kotha", nativeWord: "కొత్త", meaning: "New", transliteration: "ko-tha" },
            { word: "Patha", nativeWord: "పాత", meaning: "Old", transliteration: "paa-tha" }
        ],
        13: [
            { word: "Battegalu", nativeWord: "బట్టలు", meaning: "Clothes", transliteration: "bat-ta-lu" },
            { word: "Chokka", nativeWord: "చొక్కా", meaning: "Shirt", transliteration: "chok-ka" },
            { word: "Cheera", nativeWord: "చీర", meaning: "Saree", transliteration: "chee-ra" },
            { word: "Topi", nativeWord: "టోపీ", meaning: "Hat/Cap", transliteration: "to-pee" },
            { word: "Cheppulu", nativeWord: "చెప్పులు", meaning: "Shoes/Sandals", transliteration: "chep-pu-lu" },
            { word: "Sanchi", nativeWord: "సంచి", meaning: "Bag", transliteration: "san-chi" },
            { word: "Gadiyaram", nativeWord: "గడియారం", meaning: "Watch/Clock", transliteration: "ga-di-yaa-ram" },
            { word: "Addalu", nativeWord: "అద్దాలు", meaning: "Glasses", transliteration: "ad-da-lu" },
            { word: "Duppati", nativeWord: "దుప్పటి", meaning: "Blanket", transliteration: "dup-pa-ti" },
            { word: "Thuvaala", nativeWord: "తువాలా", meaning: "Towel", transliteration: "thu-vaa-la" }
        ],
        14: [
            { word: "Subha rathri", nativeWord: "శుభ రాత్రి", meaning: "Good Night", transliteration: "su-bha-raath-ri" },
            { word: "Jagrathe", nativeWord: "జాగ్రత్త", meaning: "Take care", transliteration: "jaa-grat-tha" },
            { word: "Malli kaluddam", nativeWord: "మళ్ళీ కలుద్దాం", meaning: "See you again", transliteration: "mal-lee-ka-lud-daam" },
            { word: "Artham kaaledu", nativeWord: "అర్థం కాలేదు", meaning: "I don't understand", transliteration: "ar-tham-kaa-lee-du" },
            { word: "Dayachesi", nativeWord: "దయచేసి", meaning: "Please", transliteration: "da-ya-chee-si" },
            { word: "Idhi bagundi", nativeWord: "ఇది బాగుంది", meaning: "It's good", transliteration: "i-di-baa-gun-di" },
            { word: "Idhi entha?", nativeWord: "ఇది ఎంత?", meaning: "How much?", transliteration: "i-di-en-tha" },
            { word: "Sahayam cheyyandi", nativeWord: "సహాయం చేయండి", meaning: "Help me", transliteration: "sa-haa-yam-che-yan-di" },
            { word: "Sari", nativeWord: "సరే", meaning: "Okay", transliteration: "sa-ree" },
            { word: "Prayanam", nativeWord: "ప్రయాణం", meaning: "Journey", transliteration: "pra-yaa-nam" }
        ]
    },
    Tamil: {
        1: [
            { word: "Vanakkam", nativeWord: "வணக்கம்", meaning: "Hello", transliteration: "va-nak-kam" },
            { word: "Nandri", nativeWord: "நன்றி", meaning: "Thank you", transliteration: "nan-dri" },
            { word: "Varaverpu", nativeWord: "வரவேற்பு", meaning: "Welcome", transliteration: "va-ra-ver-pu" },
            { word: "Yeppadi irukkireergal?", nativeWord: "எப்படி இருக்கிறீர்கள்?", meaning: "How are you?", transliteration: "yep-pa-di-i-ruk-ki-reer-gal" },
            { word: "Yen peyar", nativeWord: "என் பெயர்", meaning: "My name is", transliteration: "yen-pe-yar" },
            { word: "Poitu varugiren", nativeWord: "போயிட்டு வருகிறேன்", meaning: "Goodbye", transliteration: "poi-tu-va-ru-gi-ren" },
            { word: "Aamaam", nativeWord: "ஆமாம்", meaning: "Yes", transliteration: "aa-maam" },
            { word: "Illai", nativeWord: "இல்லை", meaning: "No", transliteration: "il-lai" },
            { word: "Mannikkavum", nativeWord: "மன்னிக்கவும்", meaning: "Sorry", transliteration: "man-nik-ka-vum" },
            { word: "Kaalai Vanakkam", nativeWord: "காலை வணக்கம்", meaning: "Good morning", transliteration: "kaa-lai-va-nak-kam" }
        ],
        2: [
            { word: "Amma", nativeWord: "அம்மா", meaning: "Mother", transliteration: "am-ma" },
            { word: "Appa", nativeWord: "அப்பா", meaning: "Father", transliteration: "ap-pa" },
            { word: "Annan", nativeWord: "அண்ணன்", meaning: "Elder Brother", transliteration: "an-nan" },
            { word: "Thambi", nativeWord: "தம்பி", meaning: "Younger Brother", transliteration: "tham-bi" },
            { word: "Akka", nativeWord: "அக்கா", meaning: "Elder Sister", transliteration: "ak-ka" },
            { word: "Thangai", nativeWord: "தங்கை", meaning: "Younger Sister", transliteration: "than-gai" },
            { word: "Thatha", nativeWord: "தாத்தா", meaning: "Grandfather", transliteration: "thaa-thaa" },
            { word: "Paatti", nativeWord: "பாட்டி", meaning: "Grandmother", transliteration: "paat-ti" },
            { word: "Nanban", nativeWord: "நண்பன்", meaning: "Friend", transliteration: "nan-ban" },
            { word: "Kudumbam", nativeWord: "குடும்பம்", meaning: "Family", transliteration: "ku-dum-bam" }
        ],
        3: [
            { word: "Ondru", nativeWord: "ஒன்று", meaning: "One", transliteration: "on-dru" },
            { word: "Irandu", nativeWord: "இரண்டு", meaning: "Two", transliteration: "i-ran-du" },
            { word: "Moondru", nativeWord: "மூன்று", meaning: "Three", transliteration: "moon-dru" },
            { word: "Naangu", nativeWord: "நான்கு", meaning: "Four", transliteration: "naan-gu" },
            { word: "Aindhu", nativeWord: "ஐந்து", meaning: "Five", transliteration: "ain-dhu" },
            { word: "Aaru", nativeWord: "ஆறு", meaning: "Six", transliteration: "aa-ru" },
            { word: "Ezhu", nativeWord: "ஏழு", meaning: "Seven", transliteration: "e-zhu" },
            { word: "Ettu", nativeWord: "எட்டு", meaning: "Eight", transliteration: "et-tu" },
            { word: "Onbadhu", nativeWord: "ஒன்பது", meaning: "Nine", transliteration: "on-ba-dhu" },
            { word: "Patthu", nativeWord: "பத்து", meaning: "Ten", transliteration: "pat-thu" }
        ],
        4: [
            { word: "Sigappu", nativeWord: "சிவப்பு", meaning: "Red", transliteration: "si-gap-pu" },
            { word: "Neelam", nativeWord: "நீலம்", meaning: "Blue", transliteration: "nee-lam" },
            { word: "Pachai", nativeWord: "பச்சை", meaning: "Green", transliteration: "pa-chai" },
            { word: "Manjal", nativeWord: "மஞ்சள்", meaning: "Yellow", transliteration: "man-jal" },
            { word: "Karuppu", nativeWord: "கருப்பு", meaning: "Black", transliteration: "ka-rup-pu" },
            { word: "Vellai", nativeWord: "வெள்ளை", meaning: "White", transliteration: "vel-lai" },
            { word: "Vattam", nativeWord: "வட்டம்", meaning: "Circle", transliteration: "vat-tam" },
            { word: "Sadhuram", nativeWord: "சதுரம்", meaning: "Square", transliteration: "sa-dhu-ram" },
            { word: "Mukkonom", nativeWord: "முக்கோணம்", meaning: "Triangle", transliteration: "muk-ko-nom" },
            { word: "Natchathiram", nativeWord: "நட்சத்திரம்", meaning: "Star", transliteration: "nat-cha-thi-ram" }
        ],
        5: [
            { word: "Unavu", nativeWord: "உணவு", meaning: "Food", transliteration: "u-na-vu" },
            { word: "Thanneer", nativeWord: "தண்ணீர்", meaning: "Water", transliteration: "than-neer" },
            { word: "Saadham", nativeWord: "சாதம்", meaning: "Rice", transliteration: "saa-dham" },
            { word: "Pazham", nativeWord: "பழம்", meaning: "Fruit", transliteration: "pa-zham" },
            { word: "Paal", nativeWord: "பால்", meaning: "Milk", transliteration: "paal" },
            { word: "Thayir", nativeWord: "தயிர்", meaning: "Curd", transliteration: "tha-yir" },
            { word: "Sarkkarai", nativeWord: "சர்க்கரை", meaning: "Sugar", transliteration: "sar-ka-rai" },
            { word: "Uppu", nativeWord: "உப்பு", meaning: "Salt", transliteration: "up-pu" },
            { word: "Theneer", nativeWord: "தேநீர்", meaning: "Tea", transliteration: "the-neer" },
            { word: "Kaapi", nativeWord: "காபி", meaning: "Coffee", transliteration: "kaa-pi" }
        ],
        6: [
            { word: "Saapidu", nativeWord: "சாப்பிடு", meaning: "Eat", transliteration: "saa-pi-du" },
            { word: "Kudi", nativeWord: "குடி", meaning: "Drink", transliteration: "ku-di" },
            { word: "Po", nativeWord: "போ", meaning: "Go", transliteration: "po" },
            { word: "Vaa", nativeWord: "வா", meaning: "Come", transliteration: "vaa" },
            { word: "Paar", nativeWord: "பார்", meaning: "See", transliteration: "paar" },
            { word: "Kael", nativeWord: "கேள்", meaning: "Listen", transliteration: "kael" },
            { word: "Paesu", nativeWord: "பேசு", meaning: "Speak", transliteration: "pae-su" },
            { word: "Thoongu", nativeWord: "தூங்கு", meaning: "Sleep", transliteration: "thoon-gu" },
            { word: "Padi", nativeWord: "படி", meaning: "Read", transliteration: "pa-di" },
            { word: "Ezhudhu", nativeWord: "எழுது", meaning: "Write", transliteration: "e-zhu-dhu" }
        ],
        7: [
            { word: "Enna", nativeWord: "என்ன", meaning: "What", transliteration: "en-na" },
            { word: "Engae", nativeWord: "எங்கே", meaning: "Where", transliteration: "en-gae" },
            { word: "Yeppozhudhu", nativeWord: "எப்போது", meaning: "When", transliteration: "yep-po-zhu-dhu" },
            { word: "Yean", nativeWord: "ஏன்", meaning: "Why", transliteration: "yean" },
            { word: "Yaar", nativeWord: "யார்", meaning: "Who", transliteration: "yaar" },
            { word: "Yeppadi", nativeWord: "எப்படி", meaning: "How", transliteration: "yep-pa-di" },
            { word: "Yedhu", nativeWord: "எது", meaning: "Which", transliteration: "ye-dhu" },
            { word: "Yevvalavu", nativeWord: "எவ்வளவு", meaning: "How many", transliteration: "yev-va-la-vu" },
            { word: "Ennudaiya", nativeWord: "என்னுடைய", meaning: "Mine", transliteration: "en-nu-dai-ya" },
            { word: "Unnudaiya", nativeWord: "உன்னுடைய", meaning: "Yours", transliteration: "un-nu-dai-ya" }
        ],
        8: [
            { word: "Naeram", nativeWord: "நேரம்", meaning: "Time", transliteration: "nae-ram" },
            { word: "Naal", nativeWord: "நாள்", meaning: "Day", transliteration: "naal" },
            { word: "Vaaram", nativeWord: "வாரம்", meaning: "Week", transliteration: "vaa-ram" },
            { word: "Maadham", nativeWord: "மாதம்", meaning: "Month", transliteration: "maa-dham" },
            { word: "Thingal", nativeWord: "திங்கள்", meaning: "Monday", transliteration: "thin-gal" },
            { word: "Sevvai", nativeWord: "செவ்வாய்", meaning: "Tuesday", transliteration: "sev-vai" },
            { word: "Budhan", nativeWord: "புதன்", meaning: "Wednesday", transliteration: "bu-dhan" },
            { word: "Viyazhan", nativeWord: "வியாழன்", meaning: "Thursday", transliteration: "vi-ya-zhan" },
            { word: "Velli", nativeWord: "வெள்ளி", meaning: "Friday", transliteration: "vel-li" },
            { word: "Vaara-irudhi", nativeWord: "வார இறுதி", meaning: "Weekend", transliteration: "vaa-ra-i-ru-dhi" }
        ],
        9: [
            { word: "Thalai", nativeWord: "தலை", meaning: "Head", transliteration: "tha-lai" },
            { word: "Kangal", nativeWord: "கண்கள்", meaning: "Eyes", transliteration: "kan-gal" },
            { word: "Kadhu", nativeWord: "காது", meaning: "Ear", transliteration: "kaa-dhu" },
            { word: "Mookku", nativeWord: "மூக்கு", meaning: "Nose", transliteration: "mook-ku" },
            { word: "Vaai", nativeWord: "வாய்", meaning: "Mouth", transliteration: "vaai" },
            { word: "Kaigal", nativeWord: "கைகள்", meaning: "Hands", transliteration: "kai-gal" },
            { word: "Kaalgal", nativeWord: "கால்கள்", meaning: "Legs", transliteration: "kaal-gal" },
            { word: "Idhayam", nativeWord: "இதயம்", meaning: "Heart", transliteration: "i-dha-yam" },
            { word: "Vayiru", nativeWord: "வயிறு", meaning: "Stomach", transliteration: "va-yi-ru" },
            { word: "Viralgal", nativeWord: "விரல்கள்", meaning: "Fingers", transliteration: "vi-ral-gal" }
        ],
        10: [
            { word: "Naai", nativeWord: "நாய்", meaning: "Dog", transliteration: "naai" },
            { word: "Poonai", nativeWord: "பூனை", meaning: "Cat", transliteration: "poo-nai" },
            { word: "Pasu", nativeWord: "பசு", meaning: "Cow", transliteration: "pa-su" },
            { word: "Yaanai", nativeWord: "யானை", meaning: "Elephant", transliteration: "yaa-nai" },
            { word: "Singam", nativeWord: "சிங்கம்", meaning: "Lion", transliteration: "sin-gam" },
            { word: "Maram", nativeWord: "மரம்", meaning: "Tree", transliteration: "ma-ram" },
            { word: "Poo", nativeWord: "பூ", meaning: "Flower", transliteration: "poo" },
            { word: "Aagasam", nativeWord: "ஆகாயம்", meaning: "Sky", transliteration: "aa-gaa-yam" },
            { word: "Sooryan", nativeWord: "சூரியன்", meaning: "Sun", transliteration: "soor-yan" },
            { word: "Chandran", nativeWord: "சந்திரன்", meaning: "Moon", transliteration: "chan-dran" }
        ],
        11: [
            { word: "Veedu", nativeWord: "வீடு", meaning: "House", transliteration: "vee-du" },
            { word: "Pallikkoodam", nativeWord: "பள்ளிக்கூடம்", meaning: "School", transliteration: "pal-lik-koo-dam" },
            { word: "Aluvalagam", nativeWord: "அலுவலகம்", meaning: "Office", transliteration: "a-lu-va-la-gam" },
            { word: "Kadai", nativeWord: "கடை", meaning: "Shop", transliteration: "ka-dai" },
            { word: "Giraamam", nativeWord: "கிராமம்", meaning: "Village", transliteration: "gi-raa-mam" },
            { word: "Naadu", nativeWord: "நாடு", meaning: "Country", transliteration: "naa-du" },
            { word: "Saalai", nativeWord: "சாலை", meaning: "Road", transliteration: "saa-lai" },
            { word: "Kovil", nativeWord: "கோவில்", meaning: "Temple", transliteration: "ko-vil" },
            { word: "Samaiyal-arai", nativeWord: "சமையலறை", meaning: "Kitchen", transliteration: "sa-mai-yal-a-rai" },
            { word: "Arai", nativeWord: "அறை", meaning: "Room", transliteration: "a-rai" }
        ],
        12: [
            { word: "Magizhchi", nativeWord: "மகிழ்ச்சி", meaning: "Happy", transliteration: "ma-gizh-chi" },
            { word: "Sogam", nativeWord: "சோகம்", meaning: "Sad", transliteration: "so-gam" },
            { word: "Kobam", nativeWord: "கோபம்", meaning: "Angry", transliteration: "ko-bam" },
            { word: "Bhayam", nativeWord: "பயம்", meaning: "Fear", transliteration: "bha-yam" },
            { word: "Periya", nativeWord: "பெரிய", meaning: "Big", transliteration: "pe-ri-ya" },
            { word: "Siriya", nativeWord: "சிறிய", meaning: "Small", transliteration: "si-ri-ya" },
            { word: "Nalla", nativeWord: "நல்ல", meaning: "Good", transliteration: "nal-la" },
            { word: "Ketta", nativeWord: "கெட்ட", meaning: "Bad", transliteration: "ket-ta" },
            { word: "Pudhiya", nativeWord: "புதிய", meaning: "New", transliteration: "pu-dhi-ya" },
            { word: "Pazhaya", nativeWord: "பழைய", meaning: "Old", transliteration: "pa-zha-ya" }
        ],
        13: [
            { word: "Aadaigal", nativeWord: "ஆடைகள்", meaning: "Clothes", transliteration: "aa-dai-gal" },
            { word: "Sattai", nativeWord: "சட்டை", meaning: "Shirt", transliteration: "sat-tai" },
            { word: "Podavai", nativeWord: "புடவை", meaning: "Saree", transliteration: "po-da-vai" },
            { word: "Thoppi", nativeWord: "தொப்பி", meaning: "Hat", transliteration: "thop-pi" },
            { word: "Seruppu", nativeWord: "செருப்பு", meaning: "Shoes", transliteration: "se-rup-pu" },
            { word: "Pai", nativeWord: "பை", meaning: "Bag", transliteration: "pai" },
            { word: "Kadigaaram", nativeWord: "கடிகாரம்", meaning: "Watch", transliteration: "ka-di-gaa-ram" },
            { word: "Kannaadi", nativeWord: "கண்ணாடி", meaning: "Glasses", transliteration: "kan-naa-di" },
            { word: "Porvai", nativeWord: "போர்வை", meaning: "Blanket", transliteration: "por-vai" },
            { word: "Thuvattum-thuni", nativeWord: "துவாலை", meaning: "Towel", transliteration: "thu-vaa-lai" }
        ],
        14: [
            { word: "Iniya Iravu", nativeWord: "இனிய இரவு", meaning: "Good Night", transliteration: "i-ni-ya-i-ra-vu" },
            { word: "Kavanamaaga iru", nativeWord: "கவனமாக இரு", meaning: "Take care", transliteration: "ka-va-na-maa-ga-i-ru" },
            { word: "Meendum santhippom", nativeWord: "மீண்டும் சந்திப்போம்", meaning: "See you again", transliteration: "meen-dum-san-thip-pom" },
            { word: "Enakku puriyavillai", nativeWord: "எனக்கு புரியவில்லை", meaning: "I don't understand", transliteration: "e-nak-ku-pu-ri-ya-vil-lai" },
            { word: "Dhayaivu seidhu", nativeWord: "தயவு செய்து", meaning: "Please", transliteration: "dha-yai-vu-sei-dhu" },
            { word: "Nandraaga irukkiradhu", nativeWord: "நன்றாக இருக்கிறது", meaning: "It's good", transliteration: "nan-draa-ga-i-ruk-ki-ra-dhu" },
            { word: "Evvalavu?", nativeWord: "எவ்வளவு?", meaning: "How much?", transliteration: "ev-va-la-vu" },
            { word: "Enakku udhavungal", nativeWord: "எனக்கு உதவுங்கள்", meaning: "Help me", transliteration: "e-nak-ku-u-dha-vun-gal" },
            { word: "Sari", nativeWord: "சரி", meaning: "Okay", transliteration: "sa-ri" },
            { word: "Payanam", nativeWord: "பயணம்", meaning: "Journey", transliteration: "pa-ya-nam" }
        ]
    }
};

module.exports = curriculumData;
